### ISSUE TITLE
Add option to view line numbers

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen2IDE#1]
[Example](http://image.prntscr.com/image/1fd4b196fc7f48f59ccc9b0eaa7af736.png)

It could make things easier to debug and read through. Maybe turn this off by default for people to keep it simple.

**Comment by mcmonkey4eva** [comment]
That's planned, and it will not be optional at all that's a key feature.

It's only not in there already because akogkosgskoagkotqi90i3t2q09 it's complicated.
